version: '3'
services:
  project-nginx:
    build:
      context: ./project/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./project:/app
    depends_on:
      - project-php-fpm
    ports:
      - "8083:80"
  project-php-fpm:
    build:
      context: ./project/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./project:/app
    depends_on:
      - project-postgres
  project-php-cli:
    build:
      context: ./project/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./project:/app
      - composer:/root/.composer/cache
    depends_on:
      - project-postgres
  project-postgres:
    image: postgres:11.2-alpine
    volumes:
      - project-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54322:5432"
volumes:
  project-postgres:
  composer: